name: MCShockwaveUHC
version: 2.0
main: net.mcshockwave.UHC.UltraHC
author: Blaxcraft
depend: [WorldEdit, HoloAPI]
softdepend: [MCShockwave, ProtocolLib]
commands:
   uhc:
   team:
      aliases: [te, teams]
   vote:
      aliases: [v, vo]
   silence:
      aliases: [sil]
   restr:
      aliases: [res]
   options:
      aliases: [opt, option]
   mole:
   mc:
   gameban:
   permban:
   incrban:
   uhcunban:
   min:
   max: